import { Product } from './types';

export const SIZES = ['XS', 'S', 'M', 'L', 'XL', 'XXL'];

export const PRODUCTS: Product[] = [
  {
    id: 'test-barca-cheap',
    team: 'FC Barcelona',
    name: 'Tréninkový dres Barcelona Top',
    priceCZK: 599,
    priceEUR: 24,
    image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=1000&auto=format&fit=crop',
    description: 'Lehký tréninkový dres pro každodenní použití. Technologie odvádějící pot a moderní střih za skvělou cenu. Ideální pro fanoušky, kteří chtějí ukázat barvy svého klubu i při tréninku.',
    isNew: true
  },
  {
    id: '1',
    team: 'Argentina',
    name: 'Dres Argentina 26 Home Authentic',
    priceCZK: 3699,
    priceEUR: 149,
    image: 'https://images.unsplash.com/photo-1617396900799-f4ec2b43c7ae?q=80&w=1000&auto=format&fit=crop',
    description: 'Oficiální domácí dres mistrů světa pro sezónu 2026. Ikonické pruhy v moderním provedení s technologiemi pro maximální výkon na hřišti.',
    isNew: true
  },
  {
    id: '2',
    team: 'Real Madrid',
    name: 'Venkovní dres Real Madrid 25/26',
    priceCZK: 2599,
    priceEUR: 105,
    image: 'https://images.unsplash.com/photo-1614632537424-6f94747e7488?q=80&w=1000&auto=format&fit=crop',
    description: 'Venkovní sada pro Krále Evropy. Odvážný design pro novou sezónu, který kombinuje eleganci s moderními prvky. Vyrobeno z recyklovaných materiálů.',
    isNew: true
  },
  {
    id: '3',
    team: 'Arsenal FC',
    name: 'Domácí dres Arsenal 25/26 Authentic',
    priceCZK: 3699,
    priceEUR: 149,
    image: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?q=80&w=1000&auto=format&fit=crop',
    description: 'Nový domácí dres Gunners pro sezónu 25/26. Čistý červeno-bílý design s detaily, které oslavují bohatou historii klubu ze severního Londýna.',
    isNew: true
  },
  {
    id: '4',
    team: 'Juventus',
    name: 'Domácí dres 23/24',
    priceCZK: 2199,
    priceEUR: 89,
    image: 'https://images.unsplash.com/photo-1518605348399-f47265886617?q=80&w=1000&auto=format&fit=crop',
    description: 'Černá a bílá. Klasika, která nestárne. Tento dres Juventusu přináší nový pohled na tradiční pruhy s efektem srsti, který symbolizuje zebru - maskota klubu.',
  },
  {
    id: '5',
    team: 'Bayern Mnichov',
    name: 'Domácí dres 23/24',
    priceCZK: 2899,
    priceEUR: 119,
    image: 'https://images.unsplash.com/photo-1616428780332-90c749b5c321?q=80&w=1000&auto=format&fit=crop',
    description: 'Dominantní červená a bílá. Dres Bayernu Mnichov je symbolem vítězství. Lehký materiál a ergonomický střih zajišťují pohodlí po celých 90 minut.',
  },
  {
    id: '6',
    team: 'AC Milan',
    name: 'Venkovní dres 23/24',
    priceCZK: 2299,
    priceEUR: 95,
    image: 'https://images.unsplash.com/photo-1510410712795-15a454d193d9?q=80&w=1000&auto=format&fit=crop',
    description: 'Oslava módy a fotbalu. Tento stříbrný dres AC Milán je inspirován módními přehlídkami v Miláně. Jedinečný vzor a prémiové detaily.',
  },
  {
    id: '7',
    team: 'FC Barcelona',
    name: 'Domácí dres 23/24',
    priceCZK: 2999,
    priceEUR: 125,
    image: 'https://images.unsplash.com/photo-1614632537197-38a17061c2bd?q=80&w=1000&auto=format&fit=crop',
    description: 'Klasické barvy Blaugranas v novém provedení. Tento dres vzdává hold ženskému týmu Barcelony a jejich úspěchům. Diamantový vzor na znaku.',
  },
  {
    id: '8',
    team: 'Paris Saint-Germain',
    name: 'Domácí dres 23/24',
    priceCZK: 2899,
    priceEUR: 119,
    image: 'https://images.unsplash.com/photo-1522778119026-d647f0565c6a?q=80&w=1000&auto=format&fit=crop',
    description: 'Pařížská elegance. Tmavě modrý základ s ikonickým červeným pruhem, který se tentokrát vytrácí do ztracena. Symbol moderního fotbalu.',
  },
  {
    id: '9',
    team: 'Liverpool FC',
    name: 'Domácí dres 23/24',
    priceCZK: 2599,
    priceEUR: 105,
    image: 'https://images.unsplash.com/photo-1518091043644-c1d4457512c6?q=80&w=1000&auto=format&fit=crop',
    description: 'Vzpomínka na Billa Shanklyho. Jednoduchý, ale úderný design s bílým límečkem a rukávy, inspirovaný dresy ze 70. let.',
  },
  {
    id: '10',
    team: 'Manchester City',
    name: 'Domácí dres 23/24',
    priceCZK: 2899,
    priceEUR: 119,
    image: 'https://images.unsplash.com/photo-1562552052-a567c963628e?q=80&w=1000&auto=format&fit=crop',
    description: 'Oslava 20 let na Etihad Stadium. Světle modrá barva doplněná o grafiku inspirovanou architekturou stadionu. Mistrovská volba.',
  },
  {
    id: '11',
    team: 'Inter Milan',
    name: 'Domácí dres 23/24',
    priceCZK: 2299,
    priceEUR: 95,
    image: 'https://images.unsplash.com/photo-1516478338927-4482c6861611?q=80&w=1000&auto=format&fit=crop',
    description: 'Nerazzurri v digitálním věku. Černo-modré pruhy jsou narušeny abstraktním vzorem, který symbolizuje propojení města a klubu.',
  },
  {
    id: '12',
    team: 'Borussia Dortmund',
    name: 'Domácí dres 23/24',
    priceCZK: 2399,
    priceEUR: 99,
    image: 'https://images.unsplash.com/photo-1549445145-ff99b632f14e?q=80&w=1000&auto=format&fit=crop',
    description: 'Žlutá zeď v pohybu. Dres navržený fanoušky pro fanoušky. Silueta stadionu Signal Iduna Park na přední straně.',
  },
  {
    id: '13',
    team: 'Chelsea FC',
    name: 'Domácí dres 23/24',
    priceCZK: 2599,
    priceEUR: 105,
    image: 'https://images.unsplash.com/photo-1563204990-2e92c207d393?q=80&w=1000&auto=format&fit=crop',
    description: '90. léta jsou zpět. Klasická modrá bez rušivých elementů, doplněná o zlaté detaily a bílé podpaží. Čistý styl.',
  },
  {
    id: '14',
    team: 'Atlético Madrid',
    name: 'Domácí dres 23/24',
    priceCZK: 2399,
    priceEUR: 99,
    image: 'https://images.unsplash.com/photo-1508101829987-7e0618458739?q=80&w=1000&auto=format&fit=crop',
    description: 'Vášeň a odvaha. Tradiční červeno-bílé pruhy v klasickém provedení. Materiál odolný proti roztržení pro ty největší bojovníky.',
  },
  {
    id: '15',
    team: 'SSC Neapol',
    name: 'Domácí dres 23/24',
    priceCZK: 2499,
    priceEUR: 100,
    image: 'https://images.unsplash.com/photo-1589487391730-58f20eb2c308?q=80&w=1000&auto=format&fit=crop',
    description: 'Šampioni Itálie. Azurově modrý dres se znakem Scudetta na hrudi. Oslava historického titulu pro město pod Vesuvem.',
    isNew: true
  }
];